# -*- coding: utf-8 -*-
"""VIT-Stego 使用帮助手册 — ReportLab 正文生成（封面由 cover_render.py 另行渲染后合并）。"""
import hashlib
import os
import sys

PDF_SKILL_DIR = r"C:\Users\32403\.zcode\cli\plugins\cache\zcode-plugins-official\pdf\0.1.7\skills\pdf"
sys.path.insert(0, os.path.join(PDF_SKILL_DIR, "scripts"))

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (CondPageBreak, HRFlowable, Image, KeepTogether,
                                PageBreak, Paragraph, Preformatted, SimpleDocTemplate,
                                Spacer, Table, TableStyle)
from reportlab.platypus.tableofcontents import TableOfContents

from pdf import install_font_fallback

# ━━ Color Palette (auto-generated by design_engine.py palette-cascade) ━━
PAGE_BG       = colors.HexColor('#f5f6f6')
SECTION_BG    = colors.HexColor('#edeeef')
CARD_BG       = colors.HexColor('#e5e9eb')
TABLE_STRIPE  = colors.HexColor('#f3f4f4')
HEADER_FILL   = colors.HexColor('#384c56')
COVER_BLOCK   = colors.HexColor('#5e747f')
BORDER        = colors.HexColor('#bfc9cf')
ICON          = colors.HexColor('#4c8eaf')
ACCENT        = colors.HexColor('#a34f33')
ACCENT_2      = colors.HexColor('#5fcd42')
TEXT_PRIMARY   = colors.HexColor('#1a1c1d')
TEXT_MUTED     = colors.HexColor('#80868a')
SEM_SUCCESS   = colors.HexColor('#397a4e')
SEM_WARNING   = colors.HexColor('#a38241')
SEM_ERROR     = colors.HexColor('#9b564f')
SEM_INFO      = colors.HexColor('#53799f')

# ── Fonts (Windows host) ──
F = r"C:\Windows\Fonts"
pdfmetrics.registerFont(TTFont('Microsoft YaHei', os.path.join(F, 'msyh.ttc'), subfontIndex=0))
pdfmetrics.registerFont(TTFont('MicrosoftYaHei-Bold', os.path.join(F, 'msyhbd.ttc'), subfontIndex=0))
pdfmetrics.registerFont(TTFont('SimHei', os.path.join(F, 'simhei.ttf')))
pdfmetrics.registerFont(TTFont('Times New Roman', os.path.join(F, 'times.ttf')))
pdfmetrics.registerFont(TTFont('Times New Roman Bold', os.path.join(F, 'timesbd.ttf')))
pdfmetrics.registerFont(TTFont('DejaVuSansMono', os.path.join(F, 'DejaVuSansMono.ttf')))
registerFontFamily('Microsoft YaHei', normal='Microsoft YaHei', bold='MicrosoftYaHei-Bold',
                   italic='Microsoft YaHei', boldItalic='MicrosoftYaHei-Bold')
registerFontFamily('SimHei', normal='SimHei', bold='SimHei')
registerFontFamily('Times New Roman', normal='Times New Roman', bold='Times New Roman Bold')
registerFontFamily('DejaVuSansMono', normal='DejaVuSansMono', bold='DejaVuSansMono')
install_font_fallback()

# ── Page geometry ──
MARGIN = 2.0 * cm
PAGE_W, PAGE_H = A4
AVAIL = PAGE_W - 2 * MARGIN  # ~481.9pt

# ── Styles ──
def ps(name, **kw):
    kw.setdefault('wordWrap', 'CJK')
    kw.setdefault('fontName', 'Microsoft YaHei')
    return ParagraphStyle(name=name, **kw)

h1 = ps('H1', fontSize=19, leading=27, textColor=HEADER_FILL, spaceBefore=18, spaceAfter=8)
h2 = ps('H2', fontSize=14, leading=20, textColor=TEXT_PRIMARY, spaceBefore=14, spaceAfter=6)
h3 = ps('H3', fontSize=11.5, leading=16, textColor=TEXT_PRIMARY, spaceBefore=10, spaceAfter=4)
body = ps('Body', fontSize=10.5, leading=17, textColor=TEXT_PRIMARY, spaceAfter=8,
          firstLineIndent=21, alignment=TA_LEFT)
body_ni = ps('BodyNI', fontSize=10.5, leading=17, textColor=TEXT_PRIMARY, spaceAfter=8)
bullet = ps('Bullet', fontSize=10.5, leading=17, textColor=TEXT_PRIMARY, spaceAfter=4,
            leftIndent=14, bulletIndent=0)
numbered = ps('Numbered', fontSize=10.5, leading=17, textColor=TEXT_PRIMARY, spaceAfter=4,
              leftIndent=16)
caption = ps('Caption', fontSize=8.5, leading=12, textColor=TEXT_MUTED,
             alignment=TA_CENTER, spaceBefore=3, spaceAfter=6)
th = ps('TH', fontSize=10, leading=14, textColor=colors.white, alignment=TA_CENTER)
td = ps('TD', fontSize=9.5, leading=13.5, textColor=TEXT_PRIMARY, alignment=TA_LEFT)
tdc = ps('TDC', fontSize=9.5, leading=13.5, textColor=TEXT_PRIMARY, alignment=TA_CENTER)
tdm = ps('TDM', fontSize=9.5, leading=13.5, textColor=TEXT_MUTED, alignment=TA_LEFT)
code_st = ParagraphStyle('Code', fontName='DejaVuSansMono', fontSize=8.5, leading=12.5,
                         textColor=TEXT_PRIMARY, backColor=CARD_BG)
toc_h = ps('TOCTitle', fontSize=19, leading=27, textColor=HEADER_FILL, spaceAfter=12)

H1_ORPHAN = (PAGE_H - 2 * MARGIN) * 0.18


def add_heading(text, style, level=0):
    key = 'h_%s' % hashlib.md5(text.encode('utf-8')).hexdigest()[:8]
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, text), style)
    p.bookmark_name = text
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p


def h1_block(story, text, first_para):
    story.append(CondPageBreak(H1_ORPHAN))
    story.append(KeepTogether([
        add_heading(text, h1, level=0),
        HRFlowable(width='100%', thickness=1.1, color=ACCENT, spaceBefore=0, spaceAfter=10),
        first_para,
    ]))


def h2_block(story, text, first):
    story.append(CondPageBreak(70))
    story.append(KeepTogether([add_heading(text, h2, level=1), first]))


def para(story, text, style=body):
    story.append(Paragraph(text, style))


def bullets(story, items):
    for it in items:
        story.append(Paragraph('• ' + it, bullet))
    story.append(Spacer(1, 6))


def code_block(story, text, label=''):
    inner = Preformatted(text, code_st)
    t = Table([[inner]], colWidths=[AVAIL * 0.96], hAlign='CENTER')
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
        ('LINEBEFORE', (0, 0), (0, -1), 2.2, ACCENT),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(Spacer(1, 4))
    story.append(t)
    if label:
        story.append(Paragraph(label, caption))
    story.append(Spacer(1, 6))


def make_table(story, header, rows, ratios, cap='', align_center_cols=()):
    widths = [r * AVAIL for r in ratios]
    data = [[Paragraph('<b>%s</b>' % c, th) for c in header]]
    for r in rows:
        cells = []
        for j, c in enumerate(r):
            st = tdc if j in align_center_cols else td
            cells.append(Paragraph(str(c), st))
        data.append(cells)
    t = Table(data, colWidths=widths, hAlign='CENTER', repeatRows=1)
    style = [
        ('BACKGROUND', (0, 0), (-1, 0), HEADER_FILL),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.4, BORDER),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        style.append(('BACKGROUND', (0, i), (-1, i),
                      TABLE_STRIPE if i % 2 == 0 else colors.white))
    t.setStyle(TableStyle(style))
    story.append(Spacer(1, 10))
    story.append(t)
    if cap:
        story.append(Paragraph(cap, caption))
    story.append(Spacer(1, 10))


def callout(story, big, label, color=ACCENT):
    stat = ParagraphStyle('Stat', fontName='Microsoft YaHei', fontSize=20, leading=26,
                          textColor=color, alignment=TA_CENTER, wordWrap='CJK')
    lab = ps('StatLab', fontSize=9, leading=13, textColor=TEXT_MUTED, alignment=TA_CENTER)
    t = Table([[Paragraph('<b>%s</b>' % big, stat)], [Paragraph(label, lab)]],
              colWidths=[AVAIL * 0.62], hAlign='CENTER')
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), TABLE_STRIPE),
        ('BOX', (0, 0), (-1, -1), 1, color),
        ('TOPPADDING', (0, 0), (0, 0), 10),
        ('BOTTOMPADDING', (0, 1), (0, 1), 10),
        ('TOPPADDING', (0, 1), (0, 1), 2),
        ('BOTTOMPADDING', (0, 0), (0, 0), 2),
    ]))
    story.append(Spacer(1, 8))
    story.append(KeepTogether(t))
    story.append(Spacer(1, 10))


def chart_auc(story, path):
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    plt.rcParams['font.sans-serif'] = ['Microsoft YaHei', 'SimHei']
    plt.rcParams['axes.unicode_minus'] = False

    cfgs = [
        ('J-UNIWARD 0.4bpp (系数图)', 1.0000, '#4c8eaf'),
        ('J-UNIWARD 0.4bpp (像素)', 1.0000, '#4c8eaf'),
        ('nsF5 1.0bpnc (系数图)', 0.9876, '#4c8eaf'),
        ('HILL 自适应 0.4bpp (657K)', 0.9094, '#384c56'),
        ('HILL 自适应 0.4bpp (240K)', 0.9036, '#384c56'),
        ('HILL 自适应 0.4bpp (96K)', 0.8873, '#384c56'),
        ('LSB 替换 0.4bpp', 0.7530, '#80868a'),
        ('HILL+STC 0.4bpp', 0.7507, '#80868a'),
        ('nsF5 0.4bpnc (系数图)', 0.5262, '#9b564f'),
        ('HILL 0.1bpp (重训)', 0.5988, '#9b564f'),
        ('无 SRM stem (原始像素)', 0.5004, '#bfc9cf'),
    ]
    cfgs = cfgs[::-1]
    names = [c[0] for c in cfgs]
    vals = [c[1] for c in cfgs]
    cols = [c[2] for c in cfgs]

    fig, ax = plt.subplots(figsize=(7.4, 4.4), dpi=200)
    bars = ax.barh(names, vals, color=cols, height=0.62)
    for b, v in zip(bars, vals):
        ax.text(v + 0.008, b.get_y() + b.get_height() / 2, '%.4f' % v,
                va='center', ha='left', fontsize=8.5, color='#1a1c1d')
    ax.axvline(0.5, color='#a34f33', linewidth=0.9, linestyle='--', alpha=0.7)
    ax.text(0.503, len(cfgs) - 0.28, '随机水平 0.50', fontsize=8, color='#a34f33')
    ax.set_xlim(0.45, 1.06)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_color('#bfc9cf')
    ax.spines['bottom'].set_color('#bfc9cf')
    ax.xaxis.grid(True, linestyle='--', linewidth=0.5, alpha=0.25)
    ax.set_axisbelow(True)
    ax.tick_params(axis='y', labelsize=8.6, length=0)
    ax.tick_params(axis='x', labelsize=8.5, colors='#80868a')
    ax.set_xlabel('held-out test AUC（3 seeds 均值，2000 封面，60 epochs）', fontsize=9)
    fig.tight_layout()
    fig.savefig(path, bbox_inches='tight', facecolor='white')
    plt.close(fig)

    from PIL import Image as PILImage
    im = PILImage.open(path)
    w, hgt = im.size
    ratio = min(AVAIL / w, 300.0 / hgt)
    story.append(Spacer(1, 10))
    story.append(Image(path, width=w * ratio, height=hgt * ratio))
    story.append(Paragraph('图 1  各工作点 held-out test AUC 总览（3 seeds 均值）', caption))
    story.append(Spacer(1, 8))


# ──────────────────────────── 内容 ────────────────────────────
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))


def header_footer(canv, doc):
    canv.saveState()
    canv.setFont('Microsoft YaHei', 7.5)
    canv.setFillColor(TEXT_MUTED)
    canv.drawString(MARGIN, PAGE_H - 1.2 * cm, 'VIT-Stego 使用帮助手册')
    canv.setStrokeColor(ACCENT)
    canv.setLineWidth(1.2)
    canv.line(MARGIN, PAGE_H - 1.35 * cm, PAGE_W - MARGIN, PAGE_H - 1.35 * cm)
    canv.setStrokeColor(BORDER)
    canv.setLineWidth(0.4)
    canv.line(MARGIN, 1.35 * cm, PAGE_W - MARGIN, 1.35 * cm)
    canv.drawString(MARGIN, 1.0 * cm, '轻量级隐写分析 ViT · F:\\VIT-stego')
    canv.drawRightString(PAGE_W - MARGIN, 1.0 * cm, '第 %d 页' % doc.page)
    canv.restoreState()


doc = TocDocTemplate(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), 'manual_body.pdf'),
    pagesize=A4, leftMargin=MARGIN, rightMargin=MARGIN,
    topMargin=2.1 * cm, bottomMargin=1.9 * cm,
    title='VIT-Stego 使用帮助手册', author='Z.ai', creator='Z.ai',
    subject='轻量级 Vision Transformer 隐写分析工具箱：安装、数据准备、训练、评估与命令行参考')

story = []

# ── 目录 ──
story.append(Paragraph('<b>目录</b>', toc_h))
toc = TableOfContents()
toc.levelStyles = [
    ps('TOC1', fontSize=11.5, leading=20, leftIndent=6, textColor=TEXT_PRIMARY),
    ps('TOC2', fontSize=10, leading=17, leftIndent=26, textColor=TEXT_MUTED),
]
story.append(toc)
story.append(PageBreak())

# ── 1 项目简介 ──
h1_block(story, '1  项目简介', Paragraph(
    'VIT-Stego 是一个自包含、CPU/GPU 单机可跑的隐写分析研究工具箱：用紧凑的 Vision '
    'Transformer（LightViT，9.6 万至 66 万参数）区分封面图（cover）与含密图（stego）。'
    '项目内置五种嵌入器——空间域的 HILL 自适应 ±1、HILL+STC、LSB 替换，以及 JPEG 域的 '
    'nsF5 与 J-UNIWARD——并配套严格的多 seed 评测协议、SRNet 基线与 MAE 预训练。'
    '本手册面向使用者，给出从环境安装到结果产出与迁移评测的完整操作说明。', body_ni))

h2_block(story, '1.1  主要结果一览', Paragraph(
    '下表汇总空间域与 JPEG 域各工作点在 2000 张 BOSSbase 封面、held-out test 划分上的'
    '表现（3 个随机种子均值 ± 标准差，60 epochs）。全部数字可由仓库内命令复现，'
    '记录存于 exp/ 目录。', body_ni))
make_table(story,
    ['输入', '嵌入方式', '参数量', 'test AUC', 'test acc'],
    [
        ['原始像素（无 SRM）', 'HILL 自适应 ±1 0.4bpp', '478,657', '0.5004 ± 0.0003', '0.5004'],
        ['SRM 残差', 'HILL 自适应 0.4bpp（默认 240K）', '240,367', '0.9036 ± 0.0188', '0.8171'],
        ['SRM 残差', 'HILL 自适应 0.4bpp（657K）', '657,583', '0.9094 ± 0.0086', '0.8092'],
        ['SRM 残差', 'LSB 替换 0.4bpp', '657,583', '0.7530 ± 0.0116', '0.6687'],
        ['SRM 残差', 'HILL + STC 0.4bpp', '657,583', '0.7507 ± 0.0158', '0.6725'],
        ['量化 DCT 系数图', 'nsF5 1.0bpnc Q75', '120,833', '0.9876 ± 0.0099', '0.9408'],
        ['量化 DCT 系数图', 'J-UNIWARD 0.4bpp Q75', '120,833', '1.0000 ± 0.0000', '0.9962'],
        ['JPEG 解压像素', 'J-UNIWARD 0.4bpp Q75', '240,367', '1.0000 ± 0.0000', '1.0000'],
    ],
    [0.20, 0.34, 0.13, 0.18, 0.15],
    cap='表 1  主要基准结果（2000 封面，3 seeds，60 epochs）',
    align_center_cols=(2, 3, 4))
chart_auc(story, os.path.join(os.path.dirname(os.path.abspath(__file__)), 'auc_chart.png'))

h2_block(story, '1.2  两条关键结论', Paragraph(
    '理解这两点是用好本工具箱的前提，也解释了默认参数为何如此设定。', body_ni))
bullets(story, [
    '<b>残差 stem 是检测能否成立的关键。</b>纯 ViT 直接吃原始像素时恰好停在随机水平'
    '（AUC 0.5004）；前置一个冻结的 SRM-30 高通残差 stem（JPEG 域则直接使用量化 DCT '
    '系数图）才能把 ±1 量级的嵌入信号送到网络。',
    '<b>检测器要小不要大。</b>24 万参数的默认配置与 66 万参数版本在误差范围内不可区分，'
    '而参数量少 2.7 倍；9.6 万参数仍能保持接近 0.89 的 AUC。容量从约 19 万参数起进入平台期。',
])

# ── 2 环境要求与安装 ──
h1_block(story, '2  环境要求与安装', Paragraph(
    '项目为纯 Python 实现，无网络依赖；所有产物（数据集、权重、实验记录）都写入项目目录，'
    '不污染系统盘。', body_ni))
h2_block(story, '2.1  依赖清单', Paragraph('核心依赖如下，建议 Python 3.10 及以上。', body_ni))
make_table(story,
    ['组件', '版本要求', '用途'],
    [
        ['Python', '3.10+', '运行环境'],
        ['numpy / scipy', '任意近期版本', '信号处理、嵌入器'],
        ['PyTorch', '2.0+（CPU 或 CUDA）', '训练与推理'],
        ['scikit-learn', '1.0+', 'AUC / accuracy 计算'],
        ['Pillow / matplotlib', '9.0+ / 3.5+', '图像与图表'],
        ['pytest（可选）', '任意', '仅在用 pytest 跑测试时需要'],
    ],
    [0.30, 0.28, 0.42],
    cap='表 2  依赖组件')
h2_block(story, '2.2  安装步骤', Paragraph('在项目根目录执行：', body_ni))
code_block(story,
    'cd F:\\VIT-stego\n'
    'pip install -r requirements.txt',
    '也可手动安装：pip install numpy scipy scikit-learn pillow matplotlib torch')
h2_block(story, '2.3  数据源与目录约定', Paragraph(
    '封面图取自姊妹项目的 BOSSbase HD 图像集，路径在 scripts/prepare_data.py 顶部的 '
    'BOSS_IMAGESET 常量中定义，可用 --imageset 参数覆盖。生成的一切数据落在项目内：', body_ni))
make_table(story,
    ['目录', '内容', '说明'],
    [
        ['data/', '生成的 .npz 数据集', '已 gitignore，可随时重建'],
        ['models/', '训练得到的权重与 sidecar JSON', '已 gitignore，可重新生成'],
        ['exp/', 'benchmark / OOD 实验记录', 'scripts/summarize.py 的输入'],
        ['docs/', '本手册与构建脚本', ''],
    ],
    [0.16, 0.42, 0.42],
    cap='表 3  目录约定')

# ── 3 空间域快速开始 ──
h1_block(story, '3  空间域快速开始', Paragraph(
    '以默认的 240K 参数检测器为例，五个命令完成「数据 → 训练 → 评估 → 基准 → 自检」全流程。'
    '单张 GPU 上 60 epochs 单 seed 约 1–2 分钟，2000 张封面数据集生成约 3 分钟。', body_ni))

h2_block(story, '3.1  第一步：生成数据集', Paragraph(
    'prepare_data.py 从图像集裁剪封面并按指定嵌入方式生成配套含密图，存为一个 .npz：', body_ni))
code_block(story,
    'python scripts/prepare_data.py --n 2000 --size 256 --rate 0.4 \\\n'
    '    --method adaptive --out data/bossbase_hill_256.npz',
    '--method 可选 adaptive（HILL 自适应 ±1，默认）/ stc（HILL+STC）/ lsb（LSB 替换）')
para(story,
     '要点：--rate 是负载率（bpp，每像素嵌入比特数）；--size 是存储裁剪边长，训练时再从'
     '中随机取 128×128 视图，等效把每张封面扩成 64 个训练视图。')

h2_block(story, '3.2  第二步：训练检测器', Paragraph(
    '默认配置即 README 中的 240K 模型（--srm --truncate 4 --pool mean 已是入口脚本默认）：', body_ni))
code_block(story,
    'python scripts/train.py --data data/bossbase_hill_256.npz \\\n'
    '    --srm --truncate 4 --pool mean --epochs 60 --seed 0 \\\n'
    '    --out models/lightvit_lite_hill.pt')
para(story,
     '训练结束在权重旁写入同名词缀为 .json 的 sidecar 文件，记录全部超参、最佳 epoch 与 '
     'test AUC——后续 evaluate / eval_ood 会读取它，保证权重按训练时的配置被评估。')

h2_block(story, '3.3  第三步：评估与多 seed 基准', Paragraph(
    '评估已保存的权重，或跑真正应当引用的多 seed 数字：', body_ni))
code_block(story,
    'python scripts/evaluate.py --data data/bossbase_hill_256.npz \\\n'
    '    --ckpt models/lightvit_lite_hill.pt\n\n'
    'python scripts/benchmark.py --data data/bossbase_hill_256.npz \\\n'
    '    --srm --truncate 4 --pool mean --epochs 60 --seeds 0,1,2 --tag 2000_hill',
    '上：评估 checkpoint（自动恢复 sidecar 配置）；下：多 seed 基准（写入 exp/<tag>.json）')

h2_block(story, '3.4  第四步：自检与汇总', Paragraph('仓库自带无需 pytest 的自检与记录汇总：', body_ni))
code_block(story,
    'python tests/test_pipeline.py\n'
    'python scripts/summarize.py',
    '上：14 项不变量自检（全部 PASS 才可信）；下：exp/*.json 渲染成 markdown 表（含 OOD 表）')

# ── 4 JPEG 域工作流 ──
h1_block(story, '4  JPEG 域工作流', Paragraph(
    '真实部署中检测 JPEG 隐写时，检测器手里是 JPEG 文件本身。prepare_data.py 为此提供两种 '
    'JPEG 域嵌入器，并把「量化 DCT 系数图」与解压像素一并存入数据集，训练时用 --input coeff '
    '选择系数图输入——此时无需 SRM stem（JPEG 量化本身即高通），模型只有 120,833 参数。', body_ni))
callout(story, 'AUC 0.988 / 1.0000', 'nsF5 1.0bpnc 与 J-UNIWARD 0.4bpp 的系数域检测结果（Q75，2000 封面）', SEM_SUCCESS)

h2_block(story, '4.1  两种嵌入器', Paragraph(
    'nsF5（非收缩 F5）把负载嵌入非零 AC 系数，奇偶翻转永不产生新零，接收端仅凭含密图即可'
    '确定载体集合；负载单位 bpnc（每非零 AC 的比特数）是文献标准约定，因为固定 bpp 并非对'
    '每张图都装得下（Q75 下每图非零 AC 数在 5.5k–33k 间波动）。J-UNIWARD 用 UNIWARD 小波'
    '代价驱动 STC，摊开在每块全部 63 个 AC 上，选点代价显著低于平均。', body_ni))

h2_block(story, '4.2  生成 JPEG 域数据集', Paragraph(
    '一条命令同时得到解压像素封面/含密图与系数图（covers_c / stegos_c，DC 置零、AC 裁剪到'
    ' ±30）。注意：J-UNIWARD 逐图约 1.6 秒，2000 张约需 1 小时；nsF5 全程仅数分钟。', body_ni))
code_block(story,
    'python scripts/prepare_data.py --n 2000 --size 256 --rate 1.0 \\\n'
    '    --rate-unit bpnc --method nsf5 --quality 75 \\\n'
    '    --out data/bossbase_nsf5_256_q75_bpnc10.npz\n\n'
    'python scripts/prepare_data.py --n 2000 --size 256 --rate 0.4 \\\n'
    '    --method juniward --quality 75 --out data/bossbase_juniward_256_q75.npz',
    '上：nsF5（--rate-unit bpnc 或 bpp，此例为文献常用的 1.0 bpnc）；下：J-UNIWARD（负载单位固定为 bpp）')

h2_block(story, '4.3  在系数图上训练', Paragraph(
    'JPEG 域训练把 --input coeff 与 --pool mean 搭配，不再加 --srm：', body_ni))
code_block(story,
    'python scripts/benchmark.py --data data/bossbase_nsf5_256_q75_bpnc10.npz \\\n'
    '    --input coeff --pool mean --epochs 60 --seeds 0,1,2 \\\n'
    '    --tag 2000_nsf5_q75_bpnc10_coeff_lite',
    'coeff 输入要求 img_size 为 8 的倍数；与 --srm 互斥（脚本会直接报错）')

h2_block(story, '4.4  结果解读', Paragraph(
    'nsF5 在 0.4 bpnc 下每图平均仅改动约 1,271 个系数（2%），在本项目数据预算下两种输入都'
    '检测不了（AUC 0.52–0.54，负结果如实记录）；负载升到 1.0 bpnc（约 8.8% 系数被改）后'
    '系数域检测器达到 0.988。J-UNIWARD 0.4bpp 改动约 9,900 系数，两域输入均饱和到 1.0。'
    '弱负载部署的正确姿势见第 5 章的跨负载迁移。', body_ni))

# ── 5 OOD / 迁移评测 ──
h1_block(story, '5  OOD / 弱负载 / 迁移评测', Paragraph(
    'scripts/eval_ood.py 对训练好的 checkpoint 不做任何重训，直接在其他数据集的 held-out '
    'test 划分上评分。所有数据集按相同顺序从相同封面构建，同一 seed 选出同一批源图，因此'
    '行间差异只归因于嵌入方式的变化。', body_ni))
code_block(story,
    'python scripts/eval_ood.py --ckpt models/lightvit_lite_hill.pt \\\n'
    '    --tag lite_hill_ood \\\n'
    '    --data data/bossbase_hill_256.npz data/bossbase_hill_256_r02.npz \\\n'
    '           data/bossbase_hill_256_r01.npz data/bossbase_hill_stc_256.npz \\\n'
    '           data/bossbase_lsb_256.npz',
    '结果写入 exp/<tag>.json，并随 summarize.py 一起渲染')
make_table(story,
    ['评测类型', '目标数据', 'AUC', '解读'],
    [
        ['分布内', 'HILL 自适应 0.4bpp', '0.8994', '基准'],
        ['弱负载', 'HILL 自适应 0.2bpp', '0.7548', '平缓退化'],
        ['弱负载', 'HILL 自适应 0.1bpp', '0.6330', '接近极限'],
        ['嵌入器不匹配', 'HILL+STC 0.4bpp', '0.7474', '损失约 0.15'],
        ['嵌入器不匹配', 'LSB 替换 0.4bpp', '0.7489', '同上'],
        ['跨域', 'nsF5 JPEG 0.4bpnc', '0.5315', '空间域不迁移到 JPEG 域'],
    ],
    [0.22, 0.30, 0.14, 0.34],
    cap='表 4  HILL-0.4 训练模型的迁移评测（exp/lite_hill_ood.json）',
    align_center_cols=(2,))
h2_block(story, '5.1  已验证的迁移规律', Paragraph(
    '三条经验可直接指导部署：其一，空间域检测器不能迁移到 JPEG 域，检测器必须按域训练；'
    '其二，JPEG 域内部跨嵌入器同样不迁移（J-UNIWARD 模型在 nsF5 上为 0.50），检测器是嵌入'
    '器特异的；其三，唯一有效的正向迁移是「强负载预训练 → 弱负载部署」——1.0bpnc 系数模型'
    '直接用于 0.4bpnc 数据可得 AUC 0.7345，远高于在 0.4bpnc 上直接训练的 0.5262。', body_ni))

# ── 6 命令行参考 ──
h1_block(story, '6  命令行参考', Paragraph(
    '七个入口脚本共享同一引擎（src/engine.py），保证一次实验的 AUC 是模型的属性而非脚本的'
    '属性。常用参数如下，未列出的可用 --help 查看。', body_ni))
h2_block(story, '6.1  脚本总览', Paragraph('每个脚本一件事，输出落点固定：', body_ni))
make_table(story,
    ['脚本', '功能', '输出'],
    [
        ['prepare_data.py', '裁剪封面 + 五种嵌入', 'data/<名>.npz（含 provenance 元数据）'],
        ['train.py', '单次训练，输出 test AUC', 'models/<名>.pt + 同名 .json sidecar'],
        ['evaluate.py', '按 sidecar 配置评估 checkpoint', '终端 AUC/acc，可 --dump-probs'],
        ['benchmark.py', '多 seed 基准', 'exp/<tag>.json'],
        ['eval_ood.py', 'checkpoint 的跨数据集迁移评测', 'exp/<tag>.json'],
        ['summarize.py', '渲染全部实验记录', '终端 markdown 表'],
        ['diagnose_split.py', '复现旧划分泄漏对照实验', '终端对比曲线'],
    ],
    [0.26, 0.42, 0.32],
    cap='表 5  入口脚本总览')
h2_block(story, '6.2  训练关键参数', Paragraph('train.py / benchmark.py 共用的模型与数据参数：', body_ni))
make_table(story,
    ['参数', '默认', '说明'],
    [
        ['--model', 'vit', 'vit（LightViT）或 srnet（SRNet 基线）'],
        ['--srm / --truncate', '关 / 0', '加冻结 SRM-30 stem；truncate=T 把残差裁剪到 ±T（推荐 4）'],
        ['--input', 'pixels', 'pixels=解压像素；coeff=量化 DCT 系数图（JPEG 域，与 --srm 互斥）'],
        ['--pool', 'cls', 'cls=CLS token；mean=patch token 均值池化（推荐）'],
        ['--dim/--depth/--heads', '64/2/4', '240K 默认配置；96K 用 32/2/2，657K 用 96/4/3'],
        ['--img-size / --patch', '128 / 8', '训练视图尺寸与 patch 边长'],
        ['--epochs / --lr / --batch', '30 / 1e-3 / 32', '2000 封面建议 60 epochs'],
        ['--no-augment', '关', '关闭随机裁剪与翻转增强'],
        ['--tta', '关', '评测时对 4 个翻转变体取平均（免训练涨点）'],
        ['--rate-unit', 'bpp', 'prepare_data 专用：bpp 或 bpnc（nsF5）'],
        ['--quality', '75', 'prepare_data 专用：JPEG 质量因子'],
    ],
    [0.26, 0.15, 0.59],
    cap='表 6  常用参数速查')

# ── 7 代码结构 ──
h1_block(story, '7  代码结构', Paragraph('按「引擎 — 模型 — 嵌入器 — 入口 — 测试」五层组织：', body_ni))
make_table(story,
    ['路径', '职责'],
    [
        ['src/engine.py', '三段划分、成对同侧、训练循环、AUC 评测——所有入口共用'],
        ['src/dataset.py', 'CoverStegoDataset：随机裁剪/翻转增强、确定性验证裁剪、像素/系数双输入'],
        ['src/vit_stego.py', 'LightViT + SRMStem（冻结 SRM-30 前端）+ SDPA 注意力'],
        ['src/srnet.py', 'SRNet 基线（瓶颈 ResNet，约 1.35M 参数）'],
        ['src/mae.py', 'MAE 自监督预训练与迁移（实测无增益，保留备用）'],
        ['src/srm_filter.py', 'SRM 30 个高通核（Fridrich）'],
        ['stego/jpeg.py', '8×8 正交 DCT 编解码、Annex-K 量化表、zigzag'],
        ['stego/nsf5.py', 'nsF5：非零 AC 载体、非收缩翻转、自适应 Hamming 矩阵编码'],
        ['stego/juniward_jpeg.py', 'J-UNIWARD 代价（db8 谱分解）+ 跨距 STC'],
        ['stego/stc.py', '伴式网格码：stride-1 与跨距两种调度，含暴力最优性自检'],
        ['stego/hill.py', 'HILL 失真函数'],
        ['scripts/', '七个入口脚本（见第 6 章）'],
        ['tests/test_pipeline.py', '14 项不变量自检'],
    ],
    [0.30, 0.70],
    cap='表 7  模块一览')

# ── 8 评测协议 ──
h1_block(story, '8  评测协议要点', Paragraph(
    '本仓库的每个数字都建立在以下四条纪律上。复现或对比结果前请先确认遵守：', body_ni))
bullets(story, [
    '<b>三段划分。</b>val 只用来挑最佳 epoch，test 在最后只评分一次并被上报。'
    '取「验证集跨 epoch 最大」是乐观估计——几百个验证样本下仅选择噪声就值好几个 AUC 点。',
    '<b>封面与含密图成对同侧。</b>同一源图的 cover 与 stego 必须落在划分的同侧'
    '（engine.make_splits 已强制），否则近似重复样本泄漏到边界两侧，AUC 被内容记忆污染。',
    '<b>至少 3 个随机种子。</b>单一划分自带约 ±0.05 的纯噪声，benchmark.py 输出均值 ± 标准差'
    '与标准误，两个配置的差异要和标准误比。',
    '<b>保持原始量纲。</b>像素停留在 [0,255]、系数停留在量化值，任何 [0,1] 归一化都会'
    '抹掉 ±1 量级的嵌入信号。',
])
callout(story, '0.217 AUC', '同样的权重、同样的 epoch，泄漏划分与正确划分的验证 AUC 之差——评测协议值得较真', SEM_WARNING)

# ── 9 常见问题 ──
h1_block(story, '9  常见问题', Paragraph('按出现频率排列；其他问题可先跑 tests/test_pipeline.py 排除环境因素。', body_ni))
faq = [
    ('训练一次要多久？',
     'GPU（CUDA）上 2000 封面 60 epochs 单 seed 约 1–2 分钟，3 seeds 约 5 分钟；'
     '纯 CPU 约 4–7 倍耗时。数据生成：空间域三种嵌入每千张约 1 分钟，nsF5 2000 张约 3 分钟，'
     'J-UNIWARD 2000 张约 1 小时（1.6 秒/图）。'),
    ('显存/内存占用多大？',
     '默认 batch 32、128×128 输入、240K 参数模型，单卡 2 GB 以内即可运行；'
     'J-UNIWARD 生成阶段的内存峰值约 2 GB（256×256 代价图的批处理窗口汇聚）。'),
    ('为什么我的 nsF5 数据集检测不到？',
     '先确认两件事：训练用的是 --input coeff（系数图）而非解压像素；负载是否足够——'
     '0.4 bpnc 在 Q75 下每图平均只改约 2% 的系数，属于本数据预算下不可检测的工作点，'
     '请用 1.0 bpnc 或更高负载先验证管道。'),
    ('如何新增一种嵌入器？',
     '在 stego/ 下实现嵌入函数（输入封面数组，输出同形状含密数组）并在 prepare_data.py 的 '
     '--method 选项中注册；随后为它补一条「负载可恢复 + 改动幅度 ≤1」的测试用例。'
     '若新嵌入器定义在系数域，同步让 prepare_data 输出 covers_c/stegos_c。'),
    ('checkpoint 能否跨数据集直接用？',
     'evaluate.py / eval_ood.py 会读取权重旁的 sidecar JSON 恢复全部超参，因此权重与数据集'
     '只要空间一致（同为像素域或同为系数域、img_size 不超过存储尺寸）即可直接评估。'
     '跨域迁移本身是否成立见第 5 章。'),
    ('exp/ 里的记录格式是什么？',
     'benchmark 类记录含 test_auc_mean/std/se、逐 seed 明细与完整 config；'
     'eval_ood 记录含逐数据集 AUC/acc 与 provenance（method/rate/domain/quality）。'
     'summarize.py --filter <子串> 可按 tag 过滤。'),
    ('如何引用仓库里的数字？',
     '一律引用 benchmark.py 产出的 test AUC（3 seeds 均值 ± 标准差），并在表格标注数据集、'
     '负载率与 epochs；验证集最大 AUC 不应出现在任何结论里。'),
]
for i, (q, a) in enumerate(faq, 1):
    story.append(KeepTogether([
        Paragraph('<b>Q%d：%s</b>' % (i, q), h3),
        Paragraph(a, body_ni),
    ]))

story.append(Spacer(1, 16))
story.append(HRFlowable(width='100%', thickness=0.8, color=BORDER, spaceBefore=6, spaceAfter=8))
para(story, '本手册对应仓库 F:\\VIT-stego（Apache-2.0 License）。手册中的全部数字可由'
            '第 3、4 章命令复现，原始记录见 exp/ 目录；仓库 README 提供英文版完整说明。', tdm)

doc.multiBuild(story, onFirstPage=header_footer, onLaterPages=header_footer)
print('body OK ->', doc.filename)
